### ISSUE TITLE
Qt PDF image format plugin causes PDFs to be displayed as image 

### ISSUE THREAD

**Issue by The-Compiler** [qtwebkit/qtwebkit#1013]
Qt 5.15 [includes Qt PDF](https://wiki.qt.io/New_Features_in_Qt_5.15#Technology_Preview_Modules) as Technical Previews. This is part of QtWebEngine and installs an image plugin for PDF, e.g. `/usr/lib/qt/plugins/imageformats/libqpdf.so`.

This means that PDFs don't get downloaded anymore. Instead, a "broken image" icon gets displayed with this logged:

> Image of format 'pdf' blocked because it is not considered safe. If you are sure it is safe to do so, you can white-list the format by setting the environment variable QTWEBKIT_IMAGEFORMAT_WHITELIST=pdf

When that's set, the PDFs first page is displayed as an image. Since that's unlikely to be what anyone wants to happen, QtWebKit should probably force a download (via the `downloadRequested` signal) rather than displaying the PDF as an image.

**Comment by annulen** [comment]
Seems quite easy to fix, however I've found that this problem is not unique to pdf, any other image type which is supported by Qt plugins but not whitelisted behaves the same way. I wonder what would be the best way to solve this: should pdf be rendered if it's whitelisted, and should image formats like mng be downloaded instead of displaying broken image icon if the are not.

**Comment by annulen** [comment]
Fixed (via simplest solution) in 0443d42b04e0f99ccdf935f7216e904525abe55b
