### ISSUE TITLE
provide binary QtWebKit 5.212.0 Alpha 3 build against Qt 5.9.x 

### ISSUE THREAD

**Issue by kmike** [qtwebkit/qtwebkit#878]
Hey @annulen! How hard would it be to have a binary build for QtWebKit 5.212.0 Alpha 3 release against Qt 5.9.x, in addition to Qt 5.13? Building from source is a bit too much for CI (https://github.com/scrapinghub/splash/pull/928/), and it seems releases in this repo is the best place to store such binaries.

I haven't tried installing binaries built for qt 5.13 inside qt 5.9, but assume this doesn't work, right?

**Comment by annulen** [comment]
Release in this repo are produced by CI system of Qt (Coin). If we are going to use the same way to provide 5.9 binaries, there are several problems:
* To set up everything right, using Coin currently requires adding code to corresponding branch of https://code.qt.io/cgit/qt/qt5.git, in this case 5.9. However, 5.9 branch is in strict mode now, so merging non-essential stuff there is undesirable.I'll check if this is possible
* At the moment it's only possible to set up building QtWebKit for one branch (commit) of qt5 repository per branch of QtWebKit. This can be worked around by having branches like qtwebkit-5.212-5.9 etc., but this is quite a gross hack and I expect that some Qt folks may not like it.
* In http://download.qt.io/snapshots/ci/qtwebkit/5.212/ there is currently no way to distinguish builds with different Qt versions (in theory can be fixed on server side, but I don't have access to that scripts)

But, since we only discuss Linux here, it's possible to make builds on a different machine. In particular, I can build your dockerfile and upload it some registry

OTOH, I would really recommend you to use Qt 5.13 or at least 5.12 (LTS). I can produce 5.12 binaries in Coin for Alpha 4. By updating Qt you get a number of bugfixes, HTTP./2 support, TLS 1.3 support, etc.

>I haven't tried installing binaries built for qt 5.13 inside qt 5.9, but assume this doesn't work, right?

Right

**Comment by kmike** [comment]
Thanks @annulen for thee clarification! 

I can also build a docker image locally, or probably set up build separately (not on Travis CI), so no need for you to do this. I wondered if it makes sense to store build artifacts in releases, and not in some third-party Docker image, but if you think that's complicated, and not worth it, we can go another way.

Updating to Qt 5.13 is in todo, but it requires some actions, e.g. upgrading PyQT; also, scripts which install Qt needs to be modified, to be able to install Qt 5.13 without user interactions; I tried an easier way first (just upgrade qtwebkit).

**Comment by annulen** [comment]
FWIW, Coin is being improved to allow separate configurations for different projects (https://bugreports.qt.io/browse/COIN-199), so all limitations will hopefully be overcome someday. But I don't think I can affect its progress anyhow (Coin is closed-source)

**Comment by kaamui** [comment]
Hi @annulen ,

I didn't want to open a new issue but I think it is actually not easy to know the status of/plans on qtwebkit releases

> OTOH, I would really recommend you to use Qt 5.13 or at least 5.12 (LTS). I can produce 5.12 binaries in Coin for Alpha 4. By updating Qt you get a number of bugfixes, HTTP./2 support, TLS 1.3 support, etc.
> 

is there some nightly builds of qtwebkit somewhere for qt 5.12 or 5.13, or is the alpha3 release (June) the latest I can find without building it on my own ?

Will you communicate on your plans for alpha 4 in a close future ?

**Comment by annulen** [comment]
>is there some nightly builds of qtwebkit somewhere for qt 5.12 or 5.13, or is the alpha3 release (June) the latest I can find without building it on my own ?

Sure, you can find latest build (against 5.13.1 as of now) at http://download.qt.io/snapshots/ci/qtwebkit/5.212/1570542016/

>Will you communicate on your plans for alpha 4 in a close future ?

Latest snapshot is probably good to go, however I wanted to get tests running in CI on all platforms before announcing it. However, things got stalled on Coin side - they were delaying production update, which seems to be finally happening today

It can be released

**Comment by kmike** [comment]
@annulen TIL about snapshots. Do you think you can add information about them somewhere (readme, wiki)?

**Comment by kaamui** [comment]
> @annulen TIL about snapshots. Do you think you can add information about them somewhere (readme, wiki)?

I agree it could be cool to develop the informations visible by the main page/readme. If I knew what to write I would help you to do but ..

**Comment by kmike** [comment]
@annulen sorry for abusing this issue :) What's on https://download.qt.io/snapshots/ci/qtwebkit/dev/? Is it a snapshot of a more recent webkit engine which one can try? If so, what qt version is it  building against?

**Comment by annulen** [comment]
No, these are also snapshots from 5.212, but built against dev branches of other Qt modules. It will be switched to qtwebkit-dev (or newer stable branch, created from it) when qtwebkit-dev becomes more stable

**Comment by kmike** [comment]
Thanks for the clarification!
